spring:
  application:
    name: project02

  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  h2:
    console:
      enabled: true

api:
  security:
    ignored:  /api/users/**, /api/users, /api/balance, /api/transaction, /h2-console, /api/user/create

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

jwt:
  secret: UGEzLf3ug6HdJy7nEaVZjIxraYsbNIbt4AIBpgTAgTQ=
  expiration: 5000000
