spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bank
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

api:
  security:
    ignored:  /api/users/**, /api/users, /api/balance, /api/transaction, /h2-console, /api/user/create

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'


jwt:
  secret: UGEzLf3ug6HdJy7nEaVZjIxraYsbNIbt4AIBpgTAgTQ=
  expiration: 5000000
