spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bank
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

#    database-platform: org.hibernate.dialect.H2Dialect

#  security:
#    user:
#      name: test
#      password: test
    #enabled: false

api:
  security:
    ignored: /api/users, /api/v1/accounts/**, /api/balance, /api/transaction, /h2-console

#logging:
#  file:
#    name: target/student.log
#  level:
#    '[org.springframework.security]': Trace

#logging:
  #config: classpath:logback-spring.xml
#  file:
#    name: target/temp.log
#  level:
#    '[org.springframework.security]': Trace

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

